library(caTools)
library(e1071)
diabetes<-read.csv(file="/home/rishi/ALL\ WORKING\ CODES/", header=TRUE, sep=",")
View(diabetes)
str(diabetes)
temp<-sample.split(diabetes, SplitRatio=0.7)
train<-subset(diabetes, temp==TRUE)
test<-subset(diabetes, temp==FALSE)
View(train)
View(test)
head(train)
head(test)
model<-naiveBayes(as.factor(train$Outcome)~.,train)
model
#pred1<-predict(my_model,test[,-9])
pred1<-predict(model,test[,-9])
pred1
table(pred1,test$Outcome,dnn=c("predicted","Actual"))
output<-cbind(test,pred1)
View(output)