library(datasets)
data(iris)
name(iris)
dim(iris)
View(iris)
str(iris)
min(iris$Sepal.Length)
max(iris$Sepal.Length)
mean(iris$Sepal.Length)
range(iris$Sepal.Length)
sd(iris$Sepal.Length)
var(iris$Sepal.Length)
quantile(iris$Sepal.Length)
quantile(iris$Sepal.Length,c(0.3,0.6))
h<-hist(iris$Sepal.Length,main="sepal length frequencies-histogram",xlab="sepal length",xlim=c(3.5,8.5),col="blue")
h
h<-hist(iris$Sepal.Length,main="sepal length frequencies-histogram",xlab="sepal length",xlim=c(3.5,8.5),col="blue",breaks=3,border="green",las=2)
H<-hist(iris$Sepal.Length,breaks=c(4.3,4.6,4.9,5.2,5.5,5.8,6.1,6.4,6.7,7.0,7.3,7.6,7.9))
boxplot(iris)
boxplot(iris$Sepal.Length)
summary(iris$Sepal.Length)
